version: "3.9"

volumes:
  vendor:
    driver: local
  node_modules:
    driver: local

services:
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./docker/volumes/database:/var/lib/postgresql/data
    ports:
      - "54320:5432"
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./bulletinboard:/bulletinboard
      - vendor:/bulletinboard/vendor
      - node_modules:/bulletinboard/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database
